"""Write docs/SOURCES.md from the collector registry, so the register of sources, licences and rights never drifts from the code.

    python -m tools.sources_doc
"""
from __future__ import annotations

from pathlib import Path

from s33hub.collectors import CORE, DOMAINS, for_domain

HEAD = """# Sources register

Generated by `python -m tools.sources_doc` from the collector classes: edit a collector's metadata, not this file.

**Domains.** `core` is the original hub (grid, weather, planning mirrors): one database, one snapshot (`hub.sqlite.gz`), an hourly job.
Every other domain is an independent job (`.github/workflows/hub-domains.yml`) with its own small database and its own published files:
a site reads only the files it needs, a slow or failing domain cannot hold up another, and the shared snapshot does not grow.

**Tiers.** `rows`: data kept in database tables (small, queryable, accumulating). `files`: tables and files published straight to R2 and
re-uploaded only when their bytes change. `mirror`: an untouched copy of a source for a site to parse itself.

**Rights.** `open` = published under an open licence the hub relies on (named below). `check` = reuse terms not yet confirmed: such a source
must not feed paid products until its row in the site's rights register says confirmed.

"""


def main() -> int:
    out = [HEAD]
    for dom in [CORE] + DOMAINS:
        out.append(f"## {dom}\n\n| Key | Source | Publisher | Licence | Every | Tier | Rights | Used by |\n|---|---|---|---|---|---|---|---|")
        for k, c in for_domain(dom).items():
            out.append(f"| `{k}` | [{c.name}]({c.url}) | {c.publisher} | {c.licence} | {c.interval_hours:g} h | {c.tier} | {c.rights} | {', '.join(c.used_by) or '-'} |")
        out.append("")
        for k, c in for_domain(dom).items():
            out.append(f"- **`{k}`**: {c.provides}")
        out.append("")
    p = Path(__file__).resolve().parent.parent / "docs" / "SOURCES.md"
    p.parent.mkdir(exist_ok=True)
    p.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
